- name: setup prerequisites
  hosts: minecraft_server
  gather_facts: true
  become: true
  roles:
    - prerequisites
  tags:
    - prerequisites

- name: setup minecraft server
  hosts: minecraft_server
  gather_facts: false
  become: true
  roles:
    - minecraft-server
  tags:
    - minecraft-server
