- name: create minecraft user
  user:
    name: minecraft
    comment: Minecraft Server

- name: create directories for minecraft server
  file:
    path: /opt/{{ item }}
    state: directory
  with_items:
    - minecraft
    - minecraft/{{ minecraft_server_type }}

- name: download minecraft server
  get_url:
    url: "{{ minecraft_server_download_url }}"
    dest: /opt/minecraft/{{ minecraft_server_type }}/minecraft_server.jar
    mode: 0750

- name: configure minecraft server
  template:
    src: "{{ item }}.j2"
    dest: /opt/minecraft/{{ minecraft_server_type }}/{{ item }}
    owner: root
    group: root
  with_items:
    - eula.txt
    - server.properties

- name: write minecraft systemd file
  copy:
    src: minecraft@.service
    dest: /usr/lib/systemd/system/minecraft@.service
    owner: root
    group: root
    mode: 0644

- name: start and enable minecraft server
  systemd:
    name: minecraft@{{ minecraft_server_type }}
    state: started
    enabled: yes
